<a href="https://colab.research.google.com/github/donghuna/DL/blob/master/DSSW_Pytorch/02autograd_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 자동 미분, autograd 

``autograd`` 패키지는 Tensor의 모든 연산에 대해 자동 미분을 제공한다.
이는 실행-기반-정의(define-by-run) 프레임워크로, 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻이며, 역전파는 학습 과정의 매 단계마다 달라진다.  

* autograd는 PyTorch에서 핵심적인 기능을 담당하는 하부 패키지이다.  
* autograd는 텐서의 연산에 대해 자동으로 미분값을 구해주는 기능을 한다.
* 텐서 자료를 생성할 때, `requires_grad`인수를 `True`로 설정하거나 `.requires_grad_(True)`를 실행하면 그 텐서에 행해지는 모든 연산에 대한 미분값을 계산한다.   
* 계산을 멈추고 싶으면 `.detach()`함수를 이용하면 된다. 


예제를 통해 알아 보도록 하자. `requires_grad`인수를 `True`로 설정하여  Tensor를 생성했다. 

In [ ]:
import torch

In [ ]:
x = torch.rand(2, 2, requires_grad=True)
print(x)

tensor([[0.4475, 0.1027],
        [0.2622, 0.1694]], requires_grad=True)


다음으로 이 x에 연산을 수행한다. 다음 코드의 y는 연산의 결과이므로 미분 함수를 가진다. `grad_fn`속성을 출력해 미분 함수를 확인 할 수 있다. 

In [ ]:
y = torch.sum(x * 3)
print(y, y.grad_fn)

tensor(2.9451, grad_fn=<SumBackward0>) <SumBackward0 object at 0x000001C5D65E1DC8>


`y.backward()` 함수를 실행하면 x의 미분값이 자동으로 갱신된다. x의 `grad`속성을 확인하면 미분값이 들어 있는 것을 확인 할 수 있다. y를 구하기 위한 x의 연산을 수식으로 쓰면 다음과 같다. 

$$
y = \displaystyle\sum_{i=1}^4 3 \times x_i
$$

이를 $x_i$에 대해 미분 하면 미분 함수는 다음과 같다. 

$$
\dfrac{\partial y}{\partial x_i} = 3
$$

실제 미분값과 같은지 확인해보자.

In [ ]:
print(x.grad)

None


In [ ]:
y.backward(retain_graph=True)

In [ ]:
x.grad

tensor([[3., 3.],
        [3., 3.]])

* ``.backward()`` 를 호출하여 모든 변화도(gradient)를 자동으로 계산할 수 있다.  
* 모든 연산 과정을 encode 하여 순환하지 않는 그래프(acyclic graph)를 생성한다.  
* 각 tensor는 ``.grad_fn`` 속성을 갖고 있는데, 이는 ``Tensor`` 를 생성한 ``Function`` 을 참조하고 있다. 

* `backward()`함수는 자동으로 미분값을 계산해 `requires_grad`인수가 True로 설정된 변수의 `grad`속성의 값을 갱신한다.
* 미분값을 그대로 출력받아 사용하고 싶은 경우에는 `torch.autograd.grad()`함수에 출력값과 입력값을 입력하면 미분값을 출력한다. 

In [ ]:
torch.autograd.grad(y, x)

(tensor([[3., 3.],
         [3., 3.]]),)

상황에 따라 특정 연산에는 미분값을 계산하고 싶지 않은 경우에는 `.detach()`함수를 사용한다. 예를 들어, 이전 코드의 결과 값 `y`에 로지스틱 함수 연산을 수행하고 이에 대한 미분 값을 계산 하고 싶지 않은 경우에 다음처럼 할 수 있다. 

In [ ]:
y_1 = y.detach()
torch.sigmoid(y_1)

tensor(0.9500)

또한 ``with torch.no_grad():`` 로 코드 블럭을 감싸서 autograd가  
``.requires_grad=True`` 인 Tensor들의 연산 기록을 추적하는 것을 멈출 수 있다.

In [ ]:
x = torch.randn(3, requires_grad=True)

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


# Autograd 연습

autograd는 텐서의 연산에 대해 자동으로 미분값을 구해주는 기능을 한다. 텐서 자료를 생성할 때, requires_grad인수를 True로 설정하거나 .requires_grad_(True)로 설정한다.

In [ ]:
import torch

1. 다음과 같은 텐서를 생성하시오.
```
x = torch.tensor(2.0, requires_grad=True)
y = 9*x**4 + 2*x**3 + 3*x**2 + 6*x +1
```

2. y를 x에 대해 미분하고 그 값을 출력해 보시오. .backward()를 사용하면 자동으로 미분값을 계산한다.

3. 다음과 같은 텐서를 생성하시오.
```
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)
y = x**2 + z**3
```

4. 3번에서 생성한 텐서에서 y를 x에 대해 편미분한 값과 y를 z에 대해 편미분한 값을 출력하시오.

5. 3번에서 생성한 x의 값을 출력해 보시오. .data를 사용한다.